---
# tasks file for webserver

- name: Install Httpd software
  package:
          name: "httpd"
          state: present

- name: Copy website
  copy:
          content: "Hi I am {{ ansible_facts['default_ipv4']['address'] }}"
          dest: /var/www/html/index.html

- name: Httpd service start
  service:
          name: "httpd"
          state: started
